version: "3"

services:
  crawler:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "4444:4444"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
